// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ContentStatus.
const (
	COMPLETED  ContentStatus = "COMPLETED"
	ERROR      ContentStatus = "ERROR"
	PENDING    ContentStatus = "PENDING"
	PROCESSING ContentStatus = "PROCESSING"
)

// Content defines model for Content.
type Content struct {
	// CreatedAt Data e hora de criação do conteúdo
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Description Descrição ou resumo extraído do conteúdo
	Description *string `json:"description"`

	// Id ULID do conteúdo
	Id *string `json:"id,omitempty"`

	// Provider Provedor do conteúdo (e.g., "youtube.com")
	Provider *string `json:"provider"`

	// ReadingTime Tempo de leitura estimado em minutos (para artigos)
	ReadingTime *int `json:"readingTime"`

	// Status Status atual do processamento do conteúdo
	Status *ContentStatus `json:"status,omitempty"`

	// ThumbnailPath URL para a imagem em miniatura do conteúdo
	ThumbnailPath *string `json:"thumbnailPath"`

	// Title Título extraído do conteúdo
	Title *string `json:"title"`

	// Transcript Transcrição do conteúdo (se aplicável, e.g., vídeos)
	Transcript *string `json:"transcript"`

	// Type Tipo do conteúdo (e.g., "video", "article")
	Type *string `json:"type,omitempty"`

	// UpdatedAt Data e hora da última atualização do conteúdo
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// Url URL original do conteúdo
	Url *string `json:"url,omitempty"`
}

// ContentStatus Status atual do processamento do conteúdo
type ContentStatus string

// ContentDetailResponse defines model for ContentDetailResponse.
type ContentDetailResponse = Content

// ContentListResponse defines model for ContentListResponse.
type ContentListResponse struct {
	Contents *[]Content `json:"contents,omitempty"`

	// Total Número total de conteúdos disponíveis
	Total *int `json:"total,omitempty"`
}

// CreateContentRequest defines model for CreateContentRequest.
type CreateContentRequest struct {
	// Type Tipo do conteúdo (e.g., "video", "article", "audio")
	Type string `json:"type"`

	// Url URL do conteúdo a ser processado
	Url string `json:"url"`
}

// CreateContentResponse defines model for CreateContentResponse.
type CreateContentResponse struct {
	// Id ULID do conteúdo criado
	Id *string `json:"id,omitempty"`

	// Url URL original do conteúdo
	Url *string `json:"url,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Detalhes adicionais do erro
	Details *string `json:"details"`

	// Error Mensagem de erro
	Error *string `json:"error,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// ExpiresIn Tempo de expiração do token em segundos
	ExpiresIn *int `json:"expiresIn,omitempty"`

	// Token Token JWT para autenticação
	Token *string `json:"token,omitempty"`
}

// NotFoundResponse defines model for NotFoundResponse.
type NotFoundResponse struct {
	// Error Mensagem de erro para recurso não encontrado
	Error *string `json:"error,omitempty"`
}

// NoteResponse defines model for NoteResponse.
type NoteResponse struct {
	// Body O corpo da nota
	Body *string `json:"body,omitempty"`

	// ContentId ULID do conteúdo ao qual a nota pertence
	ContentId *string `json:"contentId,omitempty"`

	// CreatedAt Data e hora de criação da nota
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Id ULID da nota
	Id *string `json:"id,omitempty"`

	// UpdatedAt Data e hora da última atualização da nota
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	// Limit Limite de resultados por página
	Limit *int `json:"limit,omitempty"`

	// Offset Offset da paginação
	Offset  *int       `json:"offset,omitempty"`
	Results *[]Content `json:"results,omitempty"`

	// TotalHits Número total de resultados encontrados
	TotalHits *int `json:"totalHits,omitempty"`
}

// UpdateNoteRequest defines model for UpdateNoteRequest.
type UpdateNoteRequest struct {
	// Body O novo corpo da nota associada ao conteúdo
	Body string `json:"body"`
}

// GetContentsParams defines parameters for GetContents.
type GetContentsParams struct {
	// Limit Número máximo de resultados a retornar
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Número de itens a pular antes de começar a retornar os resultados
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetSearchParams defines parameters for GetSearch.
type GetSearchParams struct {
	// Q Termo de busca
	Q string `form:"q" json:"q"`

	// Limit Número máximo de resultados a retornar
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Número de itens a pular antes de começar a retornar os resultados
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostContentsJSONRequestBody defines body for PostContents for application/json ContentType.
type PostContentsJSONRequestBody = CreateContentRequest

// UpdateNoteJSONRequestBody defines body for UpdateNote for application/json ContentType.
type UpdateNoteJSONRequestBody = UpdateNoteRequest

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Lista todos os conteúdos
	// (GET /contents)
	GetContents(c *gin.Context, params GetContentsParams)
	// Cria um novo conteúdo para enriquecimento assíncrono
	// (POST /contents)
	PostContents(c *gin.Context)
	// Exclui um conteúdo
	// (DELETE /contents/{id})
	DeleteContentsId(c *gin.Context, id string)
	// Obtém detalhes de um conteúdo específico
	// (GET /contents/{id})
	GetContentsId(c *gin.Context, id string)
	// Atualiza a nota de um conteúdo
	// (PATCH /contents/{id})
	UpdateNote(c *gin.Context, id string)
	// Stream de eventos SSE
	// (GET /events)
	GetEvents(c *gin.Context)
	// Realiza o login do usuário
	// (POST /login)
	PostLogin(c *gin.Context)
	// Realiza uma busca nos conteúdos
	// (GET /search)
	GetSearch(c *gin.Context, params GetSearchParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetContents operation middleware
func (siw *ServerInterfaceWrapper) GetContents(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetContentsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetContents(c, params)
}

// PostContents operation middleware
func (siw *ServerInterfaceWrapper) PostContents(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostContents(c)
}

// DeleteContentsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteContentsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteContentsId(c, id)
}

// GetContentsId operation middleware
func (siw *ServerInterfaceWrapper) GetContentsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetContentsId(c, id)
}

// UpdateNote operation middleware
func (siw *ServerInterfaceWrapper) UpdateNote(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateNote(c, id)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetEvents(c)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLogin(c)
}

// GetSearch operation middleware
func (siw *ServerInterfaceWrapper) GetSearch(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchParams

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument q is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSearch(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/contents", wrapper.GetContents)
	router.POST(options.BaseURL+"/contents", wrapper.PostContents)
	router.DELETE(options.BaseURL+"/contents/:id", wrapper.DeleteContentsId)
	router.GET(options.BaseURL+"/contents/:id", wrapper.GetContentsId)
	router.PATCH(options.BaseURL+"/contents/:id", wrapper.UpdateNote)
	router.GET(options.BaseURL+"/events", wrapper.GetEvents)
	router.POST(options.BaseURL+"/login", wrapper.PostLogin)
	router.GET(options.BaseURL+"/search", wrapper.GetSearch)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaX2/bRhL/Kou9A+oAiiS7TnsVcDiktpsq53+VnKZ/bBQjciRtQ+7Su0vZbqAPE9xD",
	"0Yc8He6lr/pih9mlJEpcKmrjtAlQQA8SudyZnfn95h/1kkcqzZREaQ3vvOQmGmMK7uuBkhalpa+ZVhlq",
	"K9DdiDSCxfixuxWjibTIrFCSd/ghWGDIxkoDi5FFWsDs59l/FIsVi2i/2a+x4g2Ot5BmCfIO32vvffxw",
	"t/1w79OL3XanTZ/veIMPlU7B8g6PweJDK1LkDW7vMnrEWC3kiE8bq8IrurhfXrzKmUaTp4rhrdUwex1v",
	"UOmMTWavY1RMDUUkIGEZaGCX/BQnqNkTJSWwJ2KC7FuVs2fZJaej9kT0gj02NsG7Jm9wmScJDGg7q3MM",
	"qC7iqsbPjruH9Wq1d788P3i+/+/PDtvfPvru01778/Y37X77pP1VyDSZVhMRo65KOddqgrHSK5LYDjZH",
	"zQa75Hcqt/kAm5FKL/mDbY6iEWIhRxfkpIq0C0wzRQZKUNhcA0NjRQqxYpiyVMjcKsN2nIVBWzFSZoNM",
	"IS2OUJNQY8Hmpiqv764zsDkkdMJMqwiNgRSlrfpc5invfM/Pj04Pu6dPeIOf984Ojvp9/+Pg7OT8+Oji",
	"6JA3+FGvd9bjV2WHLJ+qmMSO83QgQSTnYMcBR/eOPaiAiRRGmBbGEOBMVAuBsbWZ6bRaonlnRToiH7Um",
	"ohV/dbN/89nz0TfRV63xdYxDyBPb/DEblYmUa7GNM62wSciNs9c2T7aiT4kJ7CGrIQ3bORsW7DrJjYjY",
	"1yJGtRXcrAbpVQuoWdyrBh22Y5BBloho9mqCSYN5vHumm+0EuwsVkSJTNVQiAqpLTl8J21GCnlFLW7kV",
	"IQDlWbxVjAU2+zUhQnnEi5/eabzNdRIGs9JiJKRn3Gbo3tzcNEshpnUDNhr/a/LPEoarqF1TZOELrgY/",
	"YmRJtSJbHaIFkfTQZEoa5y1IkrMh73z/kv9d45B3+N9ay5TXKvJda57splfLvY6FseWd1rKgX+S+C4up",
	"+7KViIX2oDXcud/KQsCyp7NfU9SKudsun85Na1gsSLHZ6wkKUzb0/l41Wgbt5ZJ4oVMPr3M0gVR/L5B3",
	"P/JYqO3RX4ezFaHADOpFgH+3eNN4nQuNMWUL0q5Yc/Vmy9bhZ6sCwFVQb1UHvMeUPdJa6XoDxY7KJlTY",
	"WUjGaBjEIhJKgjB0CNR6vY6LgIqPj3KdfMRmvzA10GIEdvZfLdQ2AZ92DBRQJyiNS9oxVoUSlYQpEpCQ",
	"k9mrRMSwnUGO1UjIWi5mYMyN0g42S3kG5Rh+MBhptFB2w2J5CBQGtQRfri23gjgV8s3onz/bWIq4qj9M",
	"nXfxNhMaTVduKBndmmVCs+oFSqqUDI5yGauVuPePT/bb7VCh6J4KCHGbPX1+URRiObFVRF7aikfx7ul4",
	"8CQSZ+Jp99lP3d1T0TVd2XsUHXQ/6b7Ivvn64OlnzWZzOxefKvuFymW8wTDbgc6rrTHKtVFMkolQEo/1",
	"erw4WAST6qrtNMZ6bQcqvqsqe8YipcmHwKRysFyqcyLkGBjQde/ZeeESAzNqoJE6BCwKs2YIvUXm7W4V",
	"QEGxa2oFvCaMVEcZ4VtE1N/V/gYM8VaVWH32CEj6jRnjbUvPN5/10W84awiTfQQdjetRmYhUBNQ/pstI",
	"ntFo8sQCFVKZ0iybvaJcWFZ5LxhM1HBoMLDzmbtOR8+AdqpEkeBuXov7qyC/FNZsUUWWDr8MBivBdLe9",
	"XRH5zEHFR4iarFUXIKSaqNUowcAYFQmKA1BXkrxt8FjLZU65avKaNrihwCrsXZ9MX5wEQaN+nPuG3v/6",
	"Yg7gp88veMNPz2gnf3cpn0opPqWNhRwqV1n7PpsfYzrQs1daKPb4vMsbfILaeCPtNtvNtkNdhhIywTv8",
	"42a7+bHLvHbslGqV25BRCJo9tEpLYHkKLBHGziEauxBlFcFAmXJrATqFn1ASKMiE5E2gzSjg8idoD+Yi",
	"SQ8NKVrUxnVYYeCls1e3IlVr0KPk5TQjMwlaf52jvqO6zFUmBYkLo4I/mJtshMk5bdTJj5EJi5JEZnkC",
	"moG0aHw/leLsZ7qyUIZssdSyRrUiDAR1C6l25bjugpVz1F67XWohXZeaZYmInJlbPxo/zlxuvkVQWGlW",
	"HdLWYx+5fqWHJGg9ukdNVuv5gA60gJFVtHQFnUE9EbHSK4xzQCpz7fsrsp/J0xT03eIkAeAS3WBESOQL",
	"iFI7nykT5EWEA3S0oHYImWJW+LpzsWWDGUgmFJ7YAGTkbsY+cDKUQ5Gg0OArsZU5Y5U258qUeaN9uPy8",
	"CI73A4RQRz9dDXnU6EwrYNx7VzrUQ+FxhMKqgOkIlPt/JChrGrYPkxsHWlCkn2fXeRHszIxSi+scI+FH",
	"4WDM7LWMtJIqTJxpY5ldWi9FPPUcStBiiE2pmhCbSlJL2cVgbliKFjx75pmeyi9M6LA56x5WWXPopM11",
	"6sa8At39qirLfkeTUsK1AykzOYFMsZ0+pmyx5oHH2/69ObrS4AV8Xd+RfZioO7qNklysOL8uFm8sURZw",
	"WSKFqvVi2hOvwWsjckplSgg2955+1+bOAVMvplYr87a/0PfW6Dsb2NkvaT1O0GQYzV4PRVSLyo1lbOit",
	"rCsKqQhf1oQi5uuZtlwf/r5unE6agY0C7xAfF50P29BG1RqiSphlK/eOypNqr7hVbdK+T27gJjSeOuMt",
	"+8lS0niPipI/L1qonDkTrUaND7VSWtCnYM1a1AhFCj8LnZdGONnYdp+AdGGJ+otISbwlq/VRT1A/7KO0",
	"7Mg9z3b6/aMHi2EuDlCTPmLoR9H/Q8MwZdZNxDVCUkw5FPP/fyC11//hUG6JgonRS35zUrR4a/0xHxqr",
	"EdJVJ5Ym5LSmw4pHm161ZjFHvJQxWOiwl5dcxJe8wy43RED/stBv4Ncu/oPhb7mxib/TbDb9tVwnpSvT",
	"S3kp702j86pG7p8g/rKb1f+QkvVHhVZfgEgwZlYxE2nIcK6DUywQ4Cvw7jtTuzE/HUIZ1u8ffaAkC59l",
	"Sa0CiZ5QiRoJd4Rwv/41UAhkYFikMUYZCRCG7eQm99MzZO5V2AOG81kOEdouXvP4GFr0QuAYo2k3rSwY",
	"IpHFkYjBhHt39zbrHWXGldd+f3BSXH1LF5ob0QIXeigrqmpW3P3jQHlQcvwiKb6/Y6wVKvRwXq05nNNz",
	"c+iWCOFo5Olg3DuO2vzyeW4iKE9tcytIgIwVO0GRCP+889cADFIaoVzkJplu8ou3oUHVE7T+7cqbprsX",
	"qP1Md0Ca1AxKr7esibWIXjBw/xkLDe3/miz/GZPltbdswTJ1YfQYCiB8mJlqTk+iiDsHk3Wz5YIeV9Pp",
	"dPr/AAAA//9SAYrQPy0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
