// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// Defines values for ContentStatus.
const (
	COMPLETED  ContentStatus = "COMPLETED"
	ERROR      ContentStatus = "ERROR"
	PENDING    ContentStatus = "PENDING"
	PROCESSING ContentStatus = "PROCESSING"
)

// Content defines model for Content.
type Content struct {
	// CreatedAt Data e hora de criação do conteúdo
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Description Descrição ou resumo extraído do conteúdo
	Description *string `json:"description"`

	// Id ULID do conteúdo
	Id *string `json:"id,omitempty"`

	// Provider Provedor do conteúdo (e.g., "youtube.com")
	Provider *string `json:"provider"`

	// ReadingTime Tempo de leitura estimado em minutos (para artigos)
	ReadingTime *int `json:"readingTime"`

	// Status Status atual do processamento do conteúdo
	Status *ContentStatus `json:"status,omitempty"`

	// ThumbnailPath URL para a imagem em miniatura do conteúdo
	ThumbnailPath *string `json:"thumbnailPath"`

	// Title Título extraído do conteúdo
	Title *string `json:"title"`

	// Transcript Transcrição do conteúdo (se aplicável, e.g., vídeos)
	Transcript *string `json:"transcript"`

	// Type Tipo do conteúdo (e.g., "video", "article")
	Type *string `json:"type,omitempty"`

	// UpdatedAt Data e hora da última atualização do conteúdo
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// Url URL original do conteúdo
	Url *string `json:"url,omitempty"`
}

// ContentStatus Status atual do processamento do conteúdo
type ContentStatus string

// ContentDetailResponse defines model for ContentDetailResponse.
type ContentDetailResponse = Content

// ContentListResponse defines model for ContentListResponse.
type ContentListResponse struct {
	Contents *[]Content `json:"contents,omitempty"`

	// Total Número total de conteúdos disponíveis
	Total *int `json:"total,omitempty"`
}

// CreateContentRequest defines model for CreateContentRequest.
type CreateContentRequest struct {
	// Type Tipo do conteúdo (e.g., "video", "article", "audio")
	Type string `json:"type"`

	// Url URL do conteúdo a ser processado
	Url string `json:"url"`
}

// CreateContentResponse defines model for CreateContentResponse.
type CreateContentResponse struct {
	// Id ULID do conteúdo criado
	Id *string `json:"id,omitempty"`

	// Url URL original do conteúdo
	Url *string `json:"url,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Details Detalhes adicionais do erro
	Details *string `json:"details"`

	// Error Mensagem de erro
	Error *string `json:"error,omitempty"`
}

// NotFoundResponse defines model for NotFoundResponse.
type NotFoundResponse struct {
	// Error Mensagem de erro para recurso não encontrado
	Error *string `json:"error,omitempty"`
}

// NoteResponse defines model for NoteResponse.
type NoteResponse struct {
	// Body O corpo da nota
	Body *string `json:"body,omitempty"`

	// ContentId ULID do conteúdo ao qual a nota pertence
	ContentId *string `json:"contentId,omitempty"`

	// CreatedAt Data e hora de criação da nota
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Id ULID da nota
	Id *string `json:"id,omitempty"`

	// UpdatedAt Data e hora da última atualização da nota
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	// Limit Limite de resultados por página
	Limit *int `json:"limit,omitempty"`

	// Offset Offset da paginação
	Offset  *int       `json:"offset,omitempty"`
	Results *[]Content `json:"results,omitempty"`

	// TotalHits Número total de resultados encontrados
	TotalHits *int `json:"totalHits,omitempty"`
}

// UpdateNoteRequest defines model for UpdateNoteRequest.
type UpdateNoteRequest struct {
	// Body O novo corpo da nota associada ao conteúdo
	Body string `json:"body"`
}

// GetContentsParams defines parameters for GetContents.
type GetContentsParams struct {
	// Limit Número máximo de resultados a retornar
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Número de itens a pular antes de começar a retornar os resultados
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetSearchParams defines parameters for GetSearch.
type GetSearchParams struct {
	// Q Termo de busca
	Q string `form:"q" json:"q"`

	// Limit Número máximo de resultados a retornar
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Número de itens a pular antes de começar a retornar os resultados
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostContentsJSONRequestBody defines body for PostContents for application/json ContentType.
type PostContentsJSONRequestBody = CreateContentRequest

// UpdateNoteJSONRequestBody defines body for UpdateNote for application/json ContentType.
type UpdateNoteJSONRequestBody = UpdateNoteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Lista todos os conteúdos
	// (GET /contents)
	GetContents(c *gin.Context, params GetContentsParams)
	// Cria um novo conteúdo para enriquecimento assíncrono
	// (POST /contents)
	PostContents(c *gin.Context)
	// Exclui um conteúdo
	// (DELETE /contents/{id})
	DeleteContentsId(c *gin.Context, id string)
	// Obtém detalhes de um conteúdo específico
	// (GET /contents/{id})
	GetContentsId(c *gin.Context, id string)
	// Atualiza a nota de um conteúdo
	// (PATCH /contents/{id})
	UpdateNote(c *gin.Context, id string)
	// Stream de eventos SSE
	// (GET /events)
	GetEvents(c *gin.Context)
	// Realiza uma busca nos conteúdos
	// (GET /search)
	GetSearch(c *gin.Context, params GetSearchParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetContents operation middleware
func (siw *ServerInterfaceWrapper) GetContents(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetContentsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetContents(c, params)
}

// PostContents operation middleware
func (siw *ServerInterfaceWrapper) PostContents(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostContents(c)
}

// DeleteContentsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteContentsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteContentsId(c, id)
}

// GetContentsId operation middleware
func (siw *ServerInterfaceWrapper) GetContentsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetContentsId(c, id)
}

// UpdateNote operation middleware
func (siw *ServerInterfaceWrapper) UpdateNote(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateNote(c, id)
}

// GetEvents operation middleware
func (siw *ServerInterfaceWrapper) GetEvents(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetEvents(c)
}

// GetSearch operation middleware
func (siw *ServerInterfaceWrapper) GetSearch(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSearchParams

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument q is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", c.Request.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSearch(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/contents", wrapper.GetContents)
	router.POST(options.BaseURL+"/contents", wrapper.PostContents)
	router.DELETE(options.BaseURL+"/contents/:id", wrapper.DeleteContentsId)
	router.GET(options.BaseURL+"/contents/:id", wrapper.GetContentsId)
	router.PATCH(options.BaseURL+"/contents/:id", wrapper.UpdateNote)
	router.GET(options.BaseURL+"/events", wrapper.GetEvents)
	router.GET(options.BaseURL+"/search", wrapper.GetSearch)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xazW7bSBJ+lUbvAuMAsqQ4DgYjYLFIbE/GWP9FSnb+FCxKZEnqDNlNdzdlewI9TLCH",
	"wRx8WuwlV77YoropiRKbjmbi7PgwgA8SSXV/XfVV1VdFv+ORSjMlUVrDe++4iaaYgvt4oKRFaeljplWG",
	"2gp0NyKNYDF+5m7FaCItMiuU5D1+CBYYsqnSwGJkkRZQ/FL8W7FYsYjWKz7Eirc4XkOaJch7fK+792T3",
	"cXd378tXj7u9Lv39wFt8rHQKlvd4DBZ3rUiRt7i9yegnxmohJ3zeWt+8hsV989urnGk0eaoYXlsNxW18",
	"B6RzNituY1RMjUUkIGEZaGBDfoYz1OyFkhLYCzFD9r3K2etsyOmofRH9xJ4Zm+BNm7e4zJMERrSc1TkG",
	"oIu4jvj1yfFhM6zu428uDr7d/8dXh93vn/7wZb/7vPtdd9A97b4MmSbTaiZi1PVdLrSaYaz02k5sB9uT",
	"dosN+Y3KbT7CdqTSIX+0zVE0Qizk5BU5qbbbK0wzRQZKUNhcA0NjRQqxYpiyVMjcKsN2nIVBWzFR5o49",
	"hbQ4QU2bGgs2N/X9Bu46A5tDQifMtIrQGEhR2rrPZZ7y3o/84ujs8PjsBW/xi/75wdFg4L8cnJ9enBy9",
	"OjrkLX7U75/3+ZuqQ1a/qpnETvN0JEEkF2CnAUf3TzypgIkUJpiWxhDgTNRIgam1mel1OqJ9Y0U6IR91",
	"ZqITv7zav/rq28l30cvO9DLGMeSJbb/NJtVAyrXYxplW2CTkxuLW5slW4VOJBLbLGoKG7ZyPy+g6zY2I",
	"2D9FjGorulkN0kMLwCzv1ZMO2zHIIEtEVLyfYdJinu8+0s12G7sLtS1FphpCiQJQDTl9JG5HCfqIWtnK",
	"PREiUJ7FW+VYYMWHhALKM178/Fnzba6TMJmVFhMhfcTdTd2rq6t2JcV0rsBG07/P/lbhcJ21G0CWvuBq",
	"9BYjS9DKanWIFkTSR5MpaZy3IEnOx7z34zv+V41j3uN/6axKXqesd51FsZu/Wa11IoytrrRRBf1D7rOw",
	"mLoPW22xRA9aw437riwELHtWfEhRK+Zuu3q6MK1hsSBgxe0Mhakaen+vni2D9nJFvMTUx8scTaDU3wvl",
	"3Zc8Fmp79jfxbG1TYAb1MsF/Xr5pvMyFxpiqBaErn3nzccs28WcrAeAU1CfpgAccskdaK91soNiFsgkJ",
	"OwvJFA2DWERCSRCGDoFab+q4CEh8fJHr5AtW/MrUSIsJ2OI/WqhtEj6tGBBQpyiNK9ox1jelUBKmLEBC",
	"zor3iYhhO4OcKfu1ymXcbJMtEXlxoTHKtVFMEhSU5GS9SaaDJdPqT22HGJvRjlR8Uwd7ziKlKYEAk8rC",
	"GpxTIafAgK57Cy6qWgzMqJFGko9YVu12iO9lWj7eKrpAsUvSiR4JI+goI/yEcPtdvVHAEJ9UpptTS2Cn",
	"35hOPlWXfPysT3/DWUOcHCDoaNrMykSkIgD/hC4jeYY6xcQCVdlMaZYV7ylRViHvdUMtiRqPDQZWPnfX",
	"6egZ0ErOEtXlgqt5FPcnL74R1mwhMSqHXyWDNYXxuLudwnjtqOIzRIO8aEoQUs3UepZgYIyKBOUBaKpX",
	"n5o8Nsq8A1cv8PSYkGPl5JFvlvgJpiNdvNdCsWcXx7zFZ6iNP8zjdrfddezIUEImeI8/aXfbT3iLZ2Cn",
	"zgydqpachCjUR6u0BJanwBJh7IJKsUslVpG7lKnqQ9Ap/IySnEdHJasDLUaJkb9Ae7DYknBoSNGiNk4m",
	"hwmSFu+vRao2KEJFxiHTnKzCe/wyR31DxRVSsowPtlY5V/IHc+1pOIjmrab9Y2TCoqQtszwBzUBaNF4U",
	"p1j8QleWYMgWK5QN0MpwDWILQXvjYtIlFeeovW630ge4ViOj/tKZufPW+JnUavEtgnet43BM28xR5Pq1",
	"RoCo9fQekayLsgAGeoCRVbR0TYBBPROx8knA5GkK+mYJNcBMijuYENX4koPUdGXKBIkf4Qgd70m0IlPM",
	"Cj9QWi7ZYgaSGeUJNgIZuZuxz2AM5VgkKDR4SbQ2DarHxYUy1cDQPm89L7PU/Xg61HfN13MPydF5jW17",
	"nwtDs6+fRSisCpiOWLf//2Rdg6x+oOQ/0IJy9aKOLeSmsyNKLS5zjISfSIIxxa2MtJIqHBnz1qo+dN6J",
	"eO6DJEGLoXBJ1YzCpbJrpT4YzA1L0YIPj0VNJaGDCZ0mZ8eH9bA4dLstMB3HvMbN/TqUVWehCZRwwjtl",
	"JicWKbYzwJQtn3nkCbV/b56stVIBZzb3Pg+UVkfXUZKLNe82ZdM7VcSSDysqkPAtu+p4gz93UqOiJEK8",
	"uPcKuTHfC9hyOR1Ym2v8Sa+P0+t8ZItf02YioMkwKm7HImqk3Z1SMvR6ywkzEsIrXSZivlkMqxrt93Wu",
	"pN4ysFHgZcyzsktgd7QcjYaoR8Sq7flMCqLeV20lH7r3SX68i25nznir3quS9h+Qbvjj0oHKmTPRelp4",
	"sGJmGR9lWGykhVAq8IPBhXrB2Z297SlIl3dI40dK4jWZZYB6hnp3gNKyI/d7tjMYHD1aTjZxhJrwiLGI",
	"qN3/LxqGKbPudbNGSMqWXzH/pphgb74LrrYlwdLmd/54WbN4bf0xd43VCOm6l1Ypyz3TY+VP2x5auxyq",
	"DWUMFnrs3ZCLeMh7bHhHivOvVfwC/tnl22p/y80m/J12u+2v5TqpXJkP5VDeG6KLOiL3ztxfdoPrf6Vk",
	"/UmJ6msQCcbMKmYiDRkuMDhggQxe4+/AmdrNvOkQyrDB4OihRlEY7Cp2Sqr5iDFuhNkYMc9zE0F12JNb",
	"QREqY8VOUSTC/94l3hEYpMCg6HIDEDcwwutQ+/sCrR+efmwo9Aq1HwWNCEnDfOVyyzKuRfQTA/f/AqGZ",
	"3J8DqT9iILUxRA9W1qXRYyiJ8EBjr4++gFEMOKBMNo2kSv6/mc/n8/8FAAD//90eclAcJwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
