worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name _;

        # 🅰️ Roteamento do Angular (Frontend)
        location / {
            root /var/www/html;
            index index.html;
            # Crucial para o roteamento do Angular (SPA) não dar 404 ao dar F5
            try_files $uri $uri/ /index.html;
        }

        # 🖼️ Thumbnails
        location /thumbnails/ {
            alias /var/www/uploads/thumbnails/;
            expires 30d;
        }

        # 🚀 API Backend
        location /api/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://api:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}