// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContent = `-- name: CreateContent :one
INSERT INTO contents (id, url, status, type)
VALUES ($1, $2, 'PENDING', $3)
RETURNING id, url, status, type, created_at, updated_at
`

type CreateContentParams struct {
	ID   string
	Url  string
	Type pgtype.Text
}

func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (Content, error) {
	row := q.db.QueryRow(ctx, createContent, arg.ID, arg.Url, arg.Type)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Status,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContent = `-- name: DeleteContent :exec
DELETE FROM contents WHERE id = $1
`

func (q *Queries) DeleteContent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteContent, id)
	return err
}

const getContentByID = `-- name: GetContentByID :one
SELECT c.id, c.url, c.status, c.type, c.created_at, c.updated_at,
       m.title, m.description, m.thumbnail_path, m.transcript, m.provider, m.reading_time, m.raw_data,
       n.id as note_id, n.body as note_body, n.created_at as note_created_at, n.updated_at as note_updated_at
FROM contents c
LEFT JOIN metadata m ON c.id = m.content_id
LEFT JOIN notes n ON c.id = n.content_id
WHERE c.id = $1
`

type GetContentByIDRow struct {
	ID            string
	Url           string
	Status        string
	Type          pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Title         pgtype.Text
	Description   pgtype.Text
	ThumbnailPath pgtype.Text
	Transcript    pgtype.Text
	Provider      pgtype.Text
	ReadingTime   pgtype.Int4
	RawData       []byte
	NoteID        pgtype.Text
	NoteBody      pgtype.Text
	NoteCreatedAt pgtype.Timestamptz
	NoteUpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetContentByID(ctx context.Context, id string) (GetContentByIDRow, error) {
	row := q.db.QueryRow(ctx, getContentByID, id)
	var i GetContentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Status,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.ThumbnailPath,
		&i.Transcript,
		&i.Provider,
		&i.ReadingTime,
		&i.RawData,
		&i.NoteID,
		&i.NoteBody,
		&i.NoteCreatedAt,
		&i.NoteUpdatedAt,
	)
	return i, err
}

const getContents = `-- name: GetContents :many
SELECT c.id, c.url, c.status, c.type, c.created_at, c.updated_at,
       m.title, m.description, m.thumbnail_path, m.transcript, m.provider, m.reading_time, m.raw_data,
       n.id as note_id, n.body as note_body, n.created_at as note_created_at, n.updated_at as note_updated_at
FROM contents c
LEFT JOIN metadata m ON c.id = m.content_id
LEFT JOIN notes n ON c.id = n.content_id
ORDER BY c.created_at DESC
LIMIT $1 OFFSET $2
`

type GetContentsParams struct {
	Limit  int32
	Offset int32
}

type GetContentsRow struct {
	ID            string
	Url           string
	Status        string
	Type          pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	Title         pgtype.Text
	Description   pgtype.Text
	ThumbnailPath pgtype.Text
	Transcript    pgtype.Text
	Provider      pgtype.Text
	ReadingTime   pgtype.Int4
	RawData       []byte
	NoteID        pgtype.Text
	NoteBody      pgtype.Text
	NoteCreatedAt pgtype.Timestamptz
	NoteUpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetContents(ctx context.Context, arg GetContentsParams) ([]GetContentsRow, error) {
	rows, err := q.db.Query(ctx, getContents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContentsRow
	for rows.Next() {
		var i GetContentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Status,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.ThumbnailPath,
			&i.Transcript,
			&i.Provider,
			&i.ReadingTime,
			&i.RawData,
			&i.NoteID,
			&i.NoteBody,
			&i.NoteCreatedAt,
			&i.NoteUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentsWithMetadata = `-- name: ListContentsWithMetadata :many
SELECT
    c.id,
    c.url,
    c.type,
    c.created_at,
    c.status,
    m.title,
    m.description,
    m.provider,
    m.thumbnail_path
FROM contents c
INNER JOIN metadata m ON m.content_id = c.id
WHERE c.status = 'COMPLETED'
ORDER BY c.created_at DESC
`

type ListContentsWithMetadataRow struct {
	ID            string
	Url           string
	Type          pgtype.Text
	CreatedAt     pgtype.Timestamptz
	Status        string
	Title         pgtype.Text
	Description   pgtype.Text
	Provider      pgtype.Text
	ThumbnailPath pgtype.Text
}

func (q *Queries) ListContentsWithMetadata(ctx context.Context) ([]ListContentsWithMetadataRow, error) {
	rows, err := q.db.Query(ctx, listContentsWithMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContentsWithMetadataRow
	for rows.Next() {
		var i ListContentsWithMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Type,
			&i.CreatedAt,
			&i.Status,
			&i.Title,
			&i.Description,
			&i.Provider,
			&i.ThumbnailPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContentStatus = `-- name: UpdateContentStatus :exec
UPDATE contents
SET status = $2, 
    updated_at = NOW()
WHERE id = $1
`

type UpdateContentStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateContentStatus(ctx context.Context, arg UpdateContentStatusParams) error {
	_, err := q.db.Exec(ctx, updateContentStatus, arg.ID, arg.Status)
	return err
}

const upsertMetadata = `-- name: UpsertMetadata :one
INSERT INTO metadata (
    content_id, 
    title, 
    description, 
    thumbnail_path, 
    transcript, 
    provider, 
    reading_time, 
    raw_data,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
ON CONFLICT (content_id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    thumbnail_path = EXCLUDED.thumbnail_path,
    transcript = EXCLUDED.transcript,
    provider = EXCLUDED.provider,
    reading_time = EXCLUDED.reading_time,
    raw_data = EXCLUDED.raw_data,
    updated_at = NOW()
RETURNING content_id, title, description, thumbnail_path, transcript, provider, reading_time, raw_data, created_at, updated_at
`

type UpsertMetadataParams struct {
	ContentID     string
	Title         pgtype.Text
	Description   pgtype.Text
	ThumbnailPath pgtype.Text
	Transcript    pgtype.Text
	Provider      pgtype.Text
	ReadingTime   pgtype.Int4
	RawData       []byte
}

func (q *Queries) UpsertMetadata(ctx context.Context, arg UpsertMetadataParams) (Metadata, error) {
	row := q.db.QueryRow(ctx, upsertMetadata,
		arg.ContentID,
		arg.Title,
		arg.Description,
		arg.ThumbnailPath,
		arg.Transcript,
		arg.Provider,
		arg.ReadingTime,
		arg.RawData,
	)
	var i Metadata
	err := row.Scan(
		&i.ContentID,
		&i.Title,
		&i.Description,
		&i.ThumbnailPath,
		&i.Transcript,
		&i.Provider,
		&i.ReadingTime,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
