// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Content struct {
	ID        string
	Url       string
	Status    string
	Type      pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ContentsTag struct {
	ContentID string
	TagID     string
}

type Metadata struct {
	ContentID     string
	Title         pgtype.Text
	Description   pgtype.Text
	ThumbnailPath pgtype.Text
	Transcript    pgtype.Text
	Provider      pgtype.Text
	ReadingTime   pgtype.Int4
	RawData       []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Note struct {
	ID        string
	ContentID string
	Body      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Tag struct {
	ID   string
	Name string
	Slug string
}
