// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package db

import (
	"context"
)

const deleteNoteByContentID = `-- name: DeleteNoteByContentID :exec
DELETE FROM notes WHERE content_id = $1
`

func (q *Queries) DeleteNoteByContentID(ctx context.Context, contentID string) error {
	_, err := q.db.Exec(ctx, deleteNoteByContentID, contentID)
	return err
}

const getNoteByContentID = `-- name: GetNoteByContentID :one
SELECT id, content_id, body, created_at, updated_at FROM notes WHERE content_id = $1
`

func (q *Queries) GetNoteByContentID(ctx context.Context, contentID string) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByContentID, contentID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNote = `-- name: UpsertNote :one
INSERT INTO notes (id, content_id, body, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (content_id) 
DO UPDATE SET 
    body = EXCLUDED.body,
    updated_at = NOW()
RETURNING id, content_id, body, created_at, updated_at
`

type UpsertNoteParams struct {
	ID        string
	ContentID string
	Body      string
}

func (q *Queries) UpsertNote(ctx context.Context, arg UpsertNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, upsertNote, arg.ID, arg.ContentID, arg.Body)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
