// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
    CreateContent(ctx context.Context, arg CreateContentParams) (Content, error)
    DeleteContent(ctx context.Context, id string) error // <--- O Mock precisa desse!
    GetContentByID(ctx context.Context, id string) (GetContentByIDRow, error)
    GetContents(ctx context.Context, arg GetContentsParams) ([]GetContentsRow, error)
    UpsertMetadata(ctx context.Context, arg UpsertMetadataParams) (Metadata, error)
    UpdateContentStatus(ctx context.Context, arg UpdateContentStatusParams) error
    UpsertNote(ctx context.Context, arg UpsertNoteParams) (Note, error)
}

var _ Querier = (*Queries)(nil)
